### PR TITLE
Use tc-lib-monitor

### PR DESCRIPTION
**Pull request by imbstack**
*This is based on the statsum branch @gregarndt made before*

This integrates statsum and sentry via the new [taskcluster-lib-monitor library](https://github.com/taskcluster/taskcluster-lib-monitor).  While I was at it, I moved to compiled babel, node 5, npm-shrinkwrap, travis, etc.

I've tested this without the mock and it appears to write to signalfx correctly. We only have 2 days left on our trial there.

**NOTE: Environment variables in heroku will need to be updated before this is deployed!**

### CODE REVIEW

**Comment by gregarndt** [comment]
re: trial

paperwork is going into selena's inbox to fix that.

**Comment by jonasfj** [comment]
@gregarndt sorry to move this to you... but I see that this tracks taskIds in memory... That hurts my tiny head, and would rather just not know about it :)

**Comment by gregarndt** [comment]
yea, it was a quick hack to just get a sense of how long tasks are waiting to get executed.  Not nice, but it has to maintain some sort of state to track that in a more real-time fashion.  I ran my hacky branch on my laptop doing it for days and the process was usually around 150mb.  I suspect that might go lower when running with a more modern version of node too.

**Comment by jonasfj** [comment]
/me always thinks in failure modes... and that was just too painful.. My head exploded...

if @imbstack  and @gregarndt agree that the design is solid.. .and that it doesn't run out of memory in a bad manner... etc.. then I'm happy...

**Comment by gregarndt** [comment]
I think that getting it up and running will tell what the memory usage patterns are like, but there should definitely be something setup to expire tasks it's tracking.  That could come from another PR.  I feel that this quarter will be spent working through these things and hashing out the unknowns of how we want this stats collector collecting and reporting stats.  I'm happy to help out and iterate on it.

**Comment by imbstack** [comment]
I think getting this out now and then landing a branch that cleans up old tasks makes sense. Heroku will also kill this every 24 hours, so we kinda/sorta get that for free.

Although, doesn't that mean that we lose all of the state of running tasks once a day? What does that do to the stats we're writing?

**Comment by imbstack** [comment]
I'm going to deploy from this branch on heroku for now, just to see if it even works at all. We can revert to an old version afterward if we're not happy with the edge cases of storing things in memory.

**Comment by imbstack** [comment]
womp

```
2016-04-13T19:00:01.560717+00:00 app[run.1]:     at Collector.handleTaskRunning (/app/lib/collector.js:93:51)
2016-04-13T19:00:01.560718+00:00 app[run.1]:     at Collector.onMessage (/app/lib/collector.js:177:21)
2016-04-13T19:00:01.560718+00:00 app[run.1]:     at null.<anonymous> (/app/lib/collector.js:255:36)
2016-04-13T19:00:01.560719+00:00 app[run.1]:     at /app/node_modules/taskcluster-client/lib/pulselistener.js:397:22
2016-04-13T19:00:01.560720+00:00 app[run.1]:     at /app/node_modules/taskcluster-client/node_modules/promise/lib/es6-extensions.js:18:19
2016-04-13T19:00:01.560721+00:00 app[run.1]:     at flush (/app/node_modules/taskcluster-client/node_modules/asap/asap.js:27:13)
2016-04-13T19:00:01.560722+00:00 app[run.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-04-13T19:00:01.560722+00:00 app[run.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-04-13T19:00:01.560839+00:00 app[run.1]: Wed, 13 Apr 2016 19:00:01 GMT taskcluster-client:PulseListener Nack (without requeueing) message {"payload":{"status":{"taskId":"Hy72dtZURtG6ZNNNQ0DslA","provisionerId":"aws-provisioner-v1","workerType":"desktop-test","schedulerId":"task-graph-scheduler","taskGroupId":"PWIL5QQaQxGWr3OV4LCXPA","deadline":"2016-04-14T18:03:19.282Z","expires":"2017-04-14T18:03:19.282Z","retriesLeft":5,"state":"running","runs":[{"runId":0,"state":"running","reasonCreated":"scheduled","scheduled":"2016-04-13T18:57:21.933Z","workerGroup":"us-west-1c","workerId":"i-04ef138e1fdf00119","takenUntil":"2016-04-13T19:20:01.185Z","started":"2016-04-13T19:00:01.271Z"}]},"runId":0,"workerGroup":"us-west-1c","workerId":"i-04ef138e1fdf00119","takenUntil":"2016-04-13T19:20:01.185Z","version":1},"exchange":"exchange/taskcluster-queue/v1/task-running","routingKey":"primary.Hy72dtZURtG6ZNNNQ0DslA.0.us-west-1c.i-04ef138e1fdf00119.aws-provisioner-v1.desktop-test.task-graph-scheduler.PWIL5QQaQxGWr3OV4LCXPA._","redelivered":true,"routes":["tc-treeherder.try.a62ac0e7e41f34202838d97ffc3bd40ea3cac1cc","tc-treeherder-stage.try.a62ac0e7e41f34202838d97ffc3bd40ea3cac1cc"],"routing":{"routingKeyKind":"primary","taskId":"Hy72dtZURtG6ZNNNQ0DslA","runId":"0","workerGroup":"us-west-1c","workerId":"i-04ef138e1fdf00119","provisionerId":"aws-provisioner-v1","workerType":"desktop-test","schedulerId":"task-graph-scheduler","taskGroupId":"PWIL5QQaQxGWr3OV4LCXPA","reserved":"_"}} from exchange/taskcluster-queue/v1/task-running
2016-04-13T19:00:06.482747+00:00 app[run.1]: Wed, 13 Apr 2016 19:00:06 GMT statsum Submitting 2 data-points with dimensionality 2 to project: tc-stats-collector
2016-04-13T19:00:06.483318+00:00 app[run.1]: Wed, 13 Apr 2016 19:00:06 GMT statsum Submitting data-point to: https://statsum.taskcluster.net/v1/project/tc-stats-collector
2016-04-13T19:00:06.803310+00:00 app[run.1]: Wed, 13 Apr 2016 19:00:06 GMT statsum Failed to send data-points with error: Error: Failed to parse msgpack payload, error: msgp: attempted to decode type "int" with method for "float64", stack: {"code":"InvalidPayload"}
```

**Pull request merged**
