### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by moraveyo**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1303225

### CODE REVIEW

**Comment by djmitche** [comment]
This is looking good so far.  One thing I noticed, though, is that `yarn lock` is not updated.  Perhaps you were using `npm` instead of `yarn` to add and remove packages?  I think you can fix this by removing `node_modules` and running `yarn` to reinstall.  You should see `yarn.lock` in `git status` after that.

You may also want to adjust .travis.yml to use node 8, which will avoid the warning from yarn about using node 7.

**Comment by moraveyo** [comment]
I believe that's it. Cannot find how to request a review.

The yarn.lock was in .gitignore - fixed it.
Also, I've upgraded the packages that don't break the tests.

**Comment by djmitche** [comment]
Github doesn't let you request a review (I don't know why) so commenting on the PR is the right thing to do :)

**Comment by djmitche** [comment]
The test failures are because we don't give permissions to pushes to PRs.. long story.

**Pull request merged**
